appVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector: 
    matchLables:
      app: auth
    strategy:
      type: RollingUpdate
      rollingupdate:
        maxSurge: 3
    template: 
      metadata:
        labels:
          app: auth
      spec: containers
        -name: auth
        image: ishaquenizamani/auth
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
            name: auth-configmap
          - secretRef:
            name: auth-secret


